import type { Job } from "./job";

export const myJobArchivedSeed: Job[] = [
  {
    id: 300,
    title: "Finance Officer",
    company: "Luma Ventures",
    location: "Ratchathewi, Bangkok",
    meta: "3 Skills Match • 2 weeks ago",
    skills: ["Accounting", "Excel", "Reporting"],
    category: "Data",
    place: "Bangkok",
    workType: "Full-time",
    workOption: "On-site",
    postedAt: "2026-04-01",
    aboutTitle: "About this job",
    companyDescription:
      "Prepare financial reports, support monthly closing, and coordinate with operations to improve reporting accuracy.",
    extraDescription:
      "You will maintain clean records, help stakeholders understand performance, and assist with audit preparation.",
    applied: true,
    archived: true,
    status: "reject",
    appliedDate: "10 Apr 2026 11:45",
  },
  {
    id: 301,
    title: "Operations Supervisor",
    company: "Metro Retail Group",
    location: "Bang Kapi, Bangkok",
    meta: "4 Skills Match • 1 week ago",
    skills: ["Team Leadership", "Planning", "Operations"],
    category: "Technology",
    place: "Bangkok",
    workType: "Full-time",
    workOption: "On-site",
    postedAt: "2026-04-10",
    aboutTitle: "About this job",
    companyDescription:
      "Oversee shift execution, coordinate store teams, and keep service quality aligned with operational targets.",
    extraDescription:
      "You will support team performance, resolve day-to-day blockers, and improve consistency across operations.",
    applied: true,
    archived: true,
    status: "accept",
    appliedDate: "18 Apr 2026 16:10",
  },
  {
    id: 302,
    title: "Business Analyst",
    company: "Northstar Consulting",
    location: "Asoke, Bangkok",
    meta: "5 Skills Match • 3 days ago",
    skills: ["SQL", "Excel", "Presentation"],
    category: "Data",
    place: "Bangkok",
    workType: "Full-time",
    workOption: "Hybrid",
    postedAt: "2026-04-18",
    aboutTitle: "About this job",
    companyDescription:
      "Work with business stakeholders, gather requirements, and turn operational problems into structured recommendations.",
    extraDescription:
      "You will help frame priorities, document insights, and coordinate with implementation teams.",
    applied: true,
    archived: true,
    status: "reject",
    appliedDate: "26 Apr 2026 10:05",
  },
  {
    id: 303,
    title: "Account Executive",
    company: "Prism Media",
    location: "Phrom Phong, Bangkok",
    meta: "2 Skills Match • 5 days ago",
    skills: ["Sales", "Negotiation", "Client Management"],
    category: "Technology",
    place: "Bangkok",
    workType: "Full-time",
    workOption: "Hybrid",
    postedAt: "2026-04-16",
    aboutTitle: "About this job",
    companyDescription:
      "Own client relationships, manage proposals, and work with internal teams to move opportunities forward.",
    extraDescription:
      "You will support pipeline health, prepare pitches, and keep communication with clients timely and clear.",
    applied: true,
    archived: true,
    status: "accept",
    appliedDate: "28 Apr 2026 14:25",
  },
];
